import type { Product, Order, Customer } from '@/types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    sku: 'WRQ-A5-MM-25',
    name: 'A5 Mixed Media Sketchbook — 25 Sheets (320 GSM)',
    nameAr: 'سكتش بوك ميكسد ميديا A5 — ٢٥ ورقة',
    category: 'Sketchbooks',
    size: 'A5',
    sheets: 25,
    gsm: 320,
    paperType: 'Mixed Media Textured Paper',
    price: 195,
    compareAt: 230,
    stock: 18,
    status: 'Active',
    image: '/products/a5-mixed-media-320gsm.jpeg',
    description: 'Heavyweight 320gsm textured paper crafted for wet media, gouache, heavy ink washes, and multi-layered watercolor sketching without buckling.',
    featured: true,
  },
  {
    sku: 'WRQ-A5-KR-40',
    name: 'A5 Kraft Paper Sketchbook — 40 Sheets (180 GSM)',
    nameAr: 'سكتش بوك كرافت A5 — ٤٠ ورقة',
    category: 'Sketchbooks',
    size: 'A5',
    sheets: 40,
    gsm: 180,
    paperType: 'Heavyweight Kraft Paper',
    price: 165,
    compareAt: 190,
    stock: 14,
    status: 'Active',
    image: '/products/a5-kraft-180gsm.jpeg',
    description: 'Earthy unbleached kraft paper with rich warm tones, ideal for white gel pens, charcoal highlights, gouache illustrations, and urban sketching.',
    featured: true,
  },
  {
    sku: 'WRQ-A5-DW-50',
    name: 'A5 Drawing Sketchbook — 50 Sheets (150 GSM)',
    nameAr: 'سكتش بوك رسم A5 — ٥٠ ورقة',
    category: 'Sketchbooks',
    size: 'A5',
    sheets: 50,
    gsm: 150,
    paperType: 'Drawing & Sketching Smooth Paper',
    price: 155,
    compareAt: 175,
    stock: 22,
    status: 'Active',
    image: '/products/a5-drawing-150gsm.jpeg',
    description: 'Daily studio sketchbook with 50 fine-tooth acid-free sheets, ideal for pencil studies, ink linework, and design concept drafting.',
    featured: true,
  },
  {
    sku: 'WRQ-A5-MM-35',
    name: 'A5 Studio Mixed Media Sketchbook — 35 Sheets (250 GSM)',
    nameAr: 'سكتش بوك A5 — ٣٥ ورقة',
    category: 'Sketchbooks',
    size: 'A5',
    sheets: 35,
    gsm: 250,
    paperType: 'Heavy Artist Mixed Media Paper',
    price: 185,
    compareAt: 210,
    stock: 12,
    status: 'Active',
    image: '/products/a5-mixed-media-250gsm.jpeg',
    description: 'Versatile 250gsm all-around sketchbook balancing thickness and page count for acrylics, markers, and mixed media experiments.',
    featured: false,
  },
  {
    sku: 'WRQ-MN-KR-40',
    name: 'Mini Pocket Sketchbook (10.5×15cm) — 40 Sheets (200 GSM)',
    nameAr: 'سكتش بوك ميني — ٤٠ ورقة',
    category: 'Sketchbooks',
    size: 'Mini (10.5×15)',
    sheets: 40,
    gsm: 200,
    paperType: 'Heavyweight Kraft Paper',
    price: 125,
    compareAt: 145,
    stock: 15,
    status: 'Active',
    image: '/products/mini-kraft-200gsm.jpeg',
    description: 'Compact pocket-sized creative journal that fits anywhere. Built for on-the-go quick sketches, cafes, and travel illustration.',
    featured: true,
  },
  {
    sku: 'WRQ-LG-DW-20',
    name: 'Large Studio Sketchbook (25×35cm) — 20 Sheets (150 GSM)',
    nameAr: 'سكتش بوك كبير ٢٥×٣٥ — ٢٠ ورقة',
    category: 'Sketchbooks',
    size: '25×35cm',
    sheets: 20,
    gsm: 150,
    paperType: 'Drawing & Sketching Smooth Paper',
    price: 215,
    compareAt: 245,
    stock: 8,
    status: 'Active',
    image: '/products/large-drawing-150gsm.jpeg',
    description: 'Expansive oversized format for anatomical studies, architecture drafts, landscape charcoal compositions, and wide spreads.',
    featured: false,
  },
  {
    sku: 'WRQ-SQ-MM-20',
    name: 'Square Sketchbook (25×25cm) — 20 Sheets (320 GSM)',
    nameAr: 'سكتش بوك مربع ٢٥×٢٥ — ٢٠ ورقة',
    category: 'Sketchbooks',
    size: '25×25cm',
    sheets: 20,
    gsm: 320,
    paperType: 'Square Mixed Media Paper',
    price: 225,
    compareAt: 260,
    stock: 5,
    status: 'Active',
    image: '/products/square-mixed-media-320gsm.jpeg',
    description: 'Artistic 1:1 square canvas with thick 320gsm cotton-blend paper tailored for Instagram portfolio pieces and botanical watercolors.',
    featured: false,
  },
  {
    sku: 'WRQ-A4-MM-20',
    name: 'A4 Master Mixed Media Sketchbook — 20 Sheets (320 GSM)',
    nameAr: 'سكتش بوك ميكسد ميديا A4 — ٢٠ ورقة',
    category: 'Sketchbooks',
    size: 'A4',
    sheets: 20,
    gsm: 320,
    paperType: 'Heavy Artist Mixed Media Paper',
    price: 250,
    compareAt: 285,
    stock: 3,
    status: 'Active',
    image: '/products/a4-mixed-media-320gsm.jpeg',
    description: 'Our flagship full-size artist sketchbook. Heavyweight 320gsm archival paper built for final works, professional commissions, and portfolio exhibitions.',
    featured: false,
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    'Order ID': 'WRQ-1042',
    'Timestamp': '2026-08-20 18:45',
    'Customer name': 'Nour El-Din Hassan',
    'Phone (WhatsApp)': '01012345678',
    'Email': 'nour.hassan@gmail.com',
    'Governorate/City': 'Cairo · New Cairo',
    'Address': 'Building 44, 5th Settlement, Near Dusit LakeView',
    'Items summary': 'A5 Mixed Media (320 GSM) ×2, Mini Pocket (200 GSM) ×1',
    'Total qty': 3,
    'Subtotal (EGP)': 515,
    'Shipping (EGP)': 50,
    'Total (EGP)': 565,
    'Payment': 'Cash on delivery',
    'Status': 'Pending',
    'WhatsApp sent?': 'No',
    'Notes': 'Please deliver after 5 PM.',
  },
  {
    'Order ID': 'WRQ-1041',
    'Timestamp': '2026-08-20 15:20',
    'Customer name': 'Salma Tarek Farouk',
    'Phone (WhatsApp)': '01298765432',
    'Email': 'salma.tarek@art.edu.eg',
    'Governorate/City': 'Giza · Dokki',
    'Address': '12 Mossadak Street, 4th floor, Apt 8',
    'Items summary': 'A4 Master Mixed Media (320 GSM) ×2, A5 Kraft (180 GSM) ×2',
    'Total qty': 4,
    'Subtotal (EGP)': 830,
    'Shipping (EGP)': 0,
    'Total (EGP)': 830,
    'Payment': 'Cash on delivery',
    'Status': 'Confirmed',
    'WhatsApp sent?': 'Yes',
    'Notes': 'Fine Arts Faculty student',
  },
  {
    'Order ID': 'WRQ-1040',
    'Timestamp': '2026-08-20 11:10',
    'Customer name': 'Omar Abdel-Rahman',
    'Phone (WhatsApp)': '01155443322',
    'Email': 'omar.rahman@outlook.com',
    'Governorate/City': 'Alexandria · Smouha',
    'Address': 'Victor Emanuel Square, Bld 19, Flat 3',
    'Items summary': 'Square Sketchbook (320 GSM) ×1, A5 Mixed Media (320 GSM) ×1',
    'Total qty': 2,
    'Subtotal (EGP)': 420,
    'Shipping (EGP)': 50,
    'Total (EGP)': 470,
    'Payment': 'Cash on delivery',
    'Status': 'Packed',
    'WhatsApp sent?': 'Yes',
    'Notes': 'Call upon arrival',
  },
  {
    'Order ID': 'WRQ-1039',
    'Timestamp': '2026-08-19 19:30',
    'Customer name': 'Yasmine Mansour',
    'Phone (WhatsApp)': '01066778899',
    'Email': 'yasmine.m@designstudio.eg',
    'Governorate/City': 'Cairo · Zamalek',
    'Address': '26th of July Corridor, Building 14B',
    'Items summary': 'A5 Kraft (180 GSM) ×3, Large Studio (150 GSM) ×1',
    'Total qty': 4,
    'Subtotal (EGP)': 710,
    'Shipping (EGP)': 50,
    'Total (EGP)': 760,
    'Payment': 'Cash on delivery',
    'Status': 'Shipped',
    'WhatsApp sent?': 'Yes',
    'Notes': 'Bosta Tracking: BST-99214',
  },
  {
    'Order ID': 'WRQ-1038',
    'Timestamp': '2026-08-19 14:15',
    'Customer name': 'Karim Adel Gouda',
    'Phone (WhatsApp)': '01511223344',
    'Email': 'karim.gouda@architect.com',
    'Governorate/City': 'Cairo · Heliopolis',
    'Address': 'Beirut Street, Building 8, Near Roxy Square',
    'Items summary': 'Large Studio (25×35cm) ×2, A5 Drawing (150 GSM) ×2',
    'Total qty': 4,
    'Subtotal (EGP)': 740,
    'Shipping (EGP)': 50,
    'Total (EGP)': 790,
    'Payment': 'Cash on delivery',
    'Status': 'Delivered',
    'WhatsApp sent?': 'Yes',
    'Notes': 'Delivered & collected 790 EGP',
  },
  {
    'Order ID': 'WRQ-1037',
    'Timestamp': '2026-08-18 16:00',
    'Customer name': 'Mariam Fathy',
    'Phone (WhatsApp)': '01044332211',
    'Email': 'mariam.f@gmail.com',
    'Governorate/City': 'Dakahlia · Mansoura',
    'Address': 'Geish Street, Near Mansoura University',
    'Items summary': 'A5 Mixed Media (320 GSM) ×1',
    'Total qty': 1,
    'Subtotal (EGP)': 195,
    'Shipping (EGP)': 50,
    'Total (EGP)': 245,
    'Payment': 'Cash on delivery',
    'Status': 'Delivered',
    'WhatsApp sent?': 'Yes',
    'Notes': 'Delivered & collected 245 EGP',
  }
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    'Phone (WhatsApp)': '01012345678',
    'Customer Name': 'Nour El-Din Hassan',
    'Email': 'nour.hassan@gmail.com',
    'Delivery Address': 'Cairo · 5th Settlement, Building 44',
    'First Order Date': '2026-08-20',
    'Total Orders': 1,
    'Total Spent (EGP)': 565,
    'Customer Tag': 'New',
    'Notes': 'Graphic designer interested in wet media paper',
  },
  {
    'Phone (WhatsApp)': '01298765432',
    'Customer Name': 'Salma Tarek Farouk',
    'Email': 'salma.tarek@art.edu.eg',
    'Delivery Address': 'Giza · 12 Mossadak Street, Dokki',
    'First Order Date': '2026-07-15',
    'Total Orders': 3,
    'Total Spent (EGP)': 1940,
    'Customer Tag': 'VIP',
    'Notes': 'Faculty of Fine Arts Zamalek student leader',
  },
  {
    'Phone (WhatsApp)': '01155443322',
    'Customer Name': 'Omar Abdel-Rahman',
    'Email': 'omar.rahman@outlook.com',
    'Delivery Address': 'Alexandria · Victor Emanuel Square, Smouha',
    'First Order Date': '2026-08-02',
    'Total Orders': 2,
    'Total Spent (EGP)': 910,
    'Customer Tag': 'Repeat',
    'Notes': 'Architectural illustrator',
  },
  {
    'Phone (WhatsApp)': '01066778899',
    'Customer Name': 'Yasmine Mansour',
    'Email': 'yasmine.m@designstudio.eg',
    'Delivery Address': 'Cairo · Zamalek, 26th of July Street',
    'First Order Date': '2026-06-20',
    'Total Orders': 4,
    'Total Spent (EGP)': 2680,
    'Customer Tag': 'VIP',
    'Notes': 'Design studio director, bulk orders for studio team',
  },
  {
    'Phone (WhatsApp)': '01511223344',
    'Customer Name': 'Karim Adel Gouda',
    'Email': 'karim.gouda@architect.com',
    'Delivery Address': 'Cairo · Heliopolis, Beirut Street',
    'First Order Date': '2026-08-19',
    'Total Orders': 1,
    'Total Spent (EGP)': 790,
    'Customer Tag': 'Active',
    'Notes': 'Prefers 25x35 oversized format for blueprints',
  },
  {
    'Phone (WhatsApp)': '01044332211',
    'Customer Name': 'Mariam Fathy',
    'Email': 'mariam.f@gmail.com',
    'Delivery Address': 'Dakahlia · Mansoura, Geish Street',
    'First Order Date': '2026-08-18',
    'Total Orders': 1,
    'Total Spent (EGP)': 245,
    'Customer Tag': 'Active',
    'Notes': 'Watercolor hobbyist in Mansoura',
  }
];
